#!/bin/zsh

# Show bundles to install
function install () {
  sudo apt-get install \
  "$(dpkg -l |
  awk '{print $2}' |
  fzf)"
}

# Show bundles to remove
function remove () {
  sudo apt-get --purge remove \
  "$(dpkg -l |
  awk '{print $2}' |
  fzf)"
  }

# Present all projects in tmuxinator
function mux () {
  tmuxinator start \
  "$(find $HOME/.tmuxinator/ -maxdepth 1 -name \*.yml |
  awk -F/ '{print $NF}' |
  sed s:.yml::g |
  fzf)" &&
  clear
}

# fd - cd to selected directory
function fd () {
  local dir
  dir=$(find ${1:-*} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

# fkill - kill process
function fkill () {
  ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9}
}

# fbr - checkout git branch
function fbr () {
  local branches branch
  branches=$(git branch) &&
  branch=$(echo "$branches" | fzf +s +m) &&
  git checkout $(echo "$branch" | sed "s/.* //")
}

# fco - checkout git commit
function fco () {
  local commits commit
  commits=$(git log --pretty=oneline --abbrev-commit --reverse) &&
  commit=$(echo "$commits" | fzf +s +m -e) &&
  git checkout $(echo "$commit" | sed "s/ .*//")
}

# fshow - git commit browser (enter for show, ctrl-d for diff, ` toggles sort)
# See: https://gist.github.com/junegunn/f4fca918e937e6bf5bad
fshow() {
  local out shas sha q k
  while out=$(
      git log --graph --color=always \
          --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
      fzf --ansi --multi --no-sort --reverse --query="$q" \
          --print-query --expect=ctrl-d --toggle-sort=\`); do
    q=$(head -1 <<< "$out")
    k=$(head -2 <<< "$out" | tail -1)
    shas=$(sed '1,2d;s/^[^a-z0-9]*//;/^$/d' <<< "$out" | awk '{print $1}')
    [ -z "$shas" ] && continue
    if [ "$k" = ctrl-d ]; then
      git diff --color=always $shas | less -R
    else
      for sha in $shas; do
        git show --color=always $sha | less -R
      done
    fi
  done
}

# fh - repeat history
function fh () {
  eval $(([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s | sed 's/ *[0-9]* *//')
}